package ru.aston.pharmacy.domain;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.AfterReturning;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * The `LoggingAspect` class is an Aspect-Oriented Programming (AOP) component
 * designed to log method calls for getters, setters, `toString`, `equals`, and `hashCode`
 * methods that are generated by Lombok. This aspect helps in debugging and monitoring
 * the behavior of objects by logging key method invocations.
 */
@Aspect
@Component
public class LoggingAspect {

    private static final Logger log = LoggerFactory.getLogger(LoggingAspect.class);

    /**
     * Logs the invocation of setter methods.
     *
     * @param joinPoint The JoinPoint object representing the intercepted method call.
     * @param newValue  The new value being passed to the setter method.
     */
    @Before("execution(* ru.aston..*.set*(*)) && args(newValue)")
    public void logSetter(JoinPoint joinPoint, Object newValue) {
        String methodName = joinPoint.getSignature().getName();
        String className = joinPoint.getTarget().getClass().getSimpleName();
        log.info("Setter called: {}.{} with new value: {}", className, methodName, newValue);
    }

    /**
     * Logs the invocation of getter methods.
     *
     * @param joinPoint The JoinPoint object representing the intercepted method call.
     * @param result   The value returned by the getter method.
     */
    @AfterReturning(pointcut = "execution(* ru.aston..*.get*())", returning = "result")
    public void logGetter(JoinPoint joinPoint, Object result) {
        String methodName = joinPoint.getSignature().getName();
        String className = joinPoint.getTarget().getClass().getSimpleName();
        log.info("Getter called: {}.{} returned: {}", className, methodName, result);
    }

    /**
     * Logs the invocation of the `toString` method.
     *
     * @param joinPoint The JoinPoint object representing the intercepted method call.
     * @param result    The string representation returned by the `toString` method.
     */
    @AfterReturning(pointcut = "execution(* ru.aston..*.toString())", returning = "result")
    public void logToString(JoinPoint joinPoint, String result) {
        String className = joinPoint.getTarget().getClass().getSimpleName();
        log.info("toString called: {}.toString() returned: {}", className, result);
    }

    /**
     * Logs the invocation of the `equals` method.
     *
     * @param joinPoint The JoinPoint object representing the intercepted method call.
     * @param other     The object being compared for equality.
     */
    @Before("execution(* ru.aston..*.equals(*)) && args(other)")
    public void logEquals(JoinPoint joinPoint, Object other) {
        String className = joinPoint.getTarget().getClass().getSimpleName();
        log.info("equals called: {}.equals({})", className, other);
    }

    /**
     * Logs the invocation of the `hashCode` method.
     *
     * @param joinPoint The JoinPoint object representing the intercepted method call.
     * @param result    The hash code value returned by the `hashCode` method.
     */
    @AfterReturning(pointcut = "execution(* ru.aston..*.hashCode())", returning = "result")
    public void logHashCode(JoinPoint joinPoint, int result) {
        String className = joinPoint.getTarget().getClass().getSimpleName();
        log.info("hashCode called: {}.hashCode() returned: {}", className, result);
    }
    /**
     * Logs the invocation of constructors within the specified package.
     *
     * @param joinPoint The JoinPoint object representing the intercepted constructor call.
     *                 Provides access to the target object and method arguments.
     */
    @AfterReturning("execution(* ru.aston..*.new(..))")
    public void logConstructor(JoinPoint joinPoint) {
        String className = joinPoint.getTarget().getClass().getSimpleName();
        Object[] args = joinPoint.getArgs();
        log.info("Constructor called: {}.{} with arguments: {}", className, className, args);
    }

    /**
     * Logs the creation of a builder instance for a class.
     *
     * @param joinPoint The JoinPoint object representing the intercepted `builder()` method call.
     *                 Provides access to the target object.
     */
    @Before("execution(* ru.aston..*.builder())")
    public void logBuilderCreation(JoinPoint joinPoint) {
        String className = joinPoint.getTarget().getClass().getSimpleName();
        log.info("Builder created for class: {}", className);
    }

    /**
     * Logs the invocation of the `build()` method for a builder.
     *
     * @param joinPoint The JoinPoint object representing the intercepted `build()` method call.
     *                 Provides access to the target object.
     */
    @Before("execution(* ru.aston..*.build())")
    public void logBuilderBuild(JoinPoint joinPoint) {
        String className = joinPoint.getTarget().getClass().getEnclosingClass().getSimpleName();
        log.info("Builder.build() called for class: {}", className);
    }
}